### ISSUE TITLE
implementation 'com.wandroid:traceroute-for-android:1.0.1' not working

### ISSUE THREAD

**Issue by adrianhartanto004** [wangjing53406/traceroute-for-android#1]
Hi there..
I tried to do `implementation 'com.wandroid:traceroute-for-android:1.0.1'` in the gradle dependencies, but it's not working.
Error : `ERROR: Failed to resolve: com.wandroid:traceroute-for-android:1.0.1
Show in Project Structure dialog
Affected Modules: app`
Meanwhile `implementation 'com.wandroid:traceroute-for-android:1.0.0'` is working, but the Activity / App crashed when there's no internet connection or wrong url at the edittext box on Devices API below 26.

**Comment by Lurzapps** [comment]
having the same problem

**Comment by kuFEAR** [comment]
ping, @wangjing53406 can you upload last version to maven? 1.0.1

**Comment by zhubinsheng** [comment]
https://mvnrepository.com/artifact/com.wandroid/traceroute-for-android
use 1.0.0

**Comment by BigBangKing** [comment]
I had this issue. I solved it, so posting as a comment in case anyone gets benefit.
Please download the project, build and see the example project. Then from your project import the library module from the example project, add dependency. Works fine at least for me.

**Comment by BigBangKing** [comment]
I had this issue. I solved it, so posting as a comment in case anyone gets benefit.
Please download and build the example project. From your project import the library module from the example project, add dependency.
Works fine at least for me.

**Comment by BigBangKing** [comment]
I worked with the example project, library worked. In case anyone benefits from this info.

**Comment by wangjing53406** [comment]
add jcenter() in root build.gradle
